### PR TITLE
Add dbus model for fru's on splitter

### PR DESCRIPTION
**Pull request by manojkiraneda**

### CODE REVIEW

**Review by jaypadath — COMMENTED** [review]
Please add some description in the commit message.

**Review by ArchanaKakani — APPROVED** [review]

**Review by jaypadath — APPROVED** [review]

**Review by Pavithrab7 — APPROVED** [review]

**Review by ArchanaKakani — COMMENTED** [review]
Deletion of the Front panel board from the map is missing inside the deleteObject function

**Comment by manojkiraneda** [comment]
> Deletion of the Front panel board from the map is missing inside the deleteObject function

its there in libpldmresponder/platform.cpp right

**Comment by ArchanaKakani** [comment]
https://github.com/ibm-openbmc/pldm/blob/1030/host-bmc/dbus/custom_dbus.cpp#L479 here we need to remove the entry from panel map

**Review by jaypadath — APPROVED** [review]

**Review by ArchanaKakani — APPROVED** [review]

**Pull request merged**
